spring:
  application:
    name: core-bank-mock-server
  jackson:
    date-format: com.backbase.openbanking.mockserver.config.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

server:
  port: 9091

mock-server:
  root-path: classpath:mock-data
  file-extension: .json
  prefix-separator: "-"

openapi:
  accountAndTransactionAPISpecification:
    base-path: /

management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
      enabled: true

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

logging:
  level:
    root: INFO