---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wiremock-studio

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-manager
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["services"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: service-manager
subjects:
  - kind: ServiceAccount
    name: wiremock-studio
roleRef:
  kind: Role
  name: service-manager
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wiremock-studio-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wiremock-studio
  labels:
    name: wiremock-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wiremock-studio
  template:
    metadata:
      labels:
        name: wiremock-studio
    spec:
      serviceAccountName: wiremock-studio
      volumes:
        - name: wiremock-data-storage
          persistentVolumeClaim:
            claimName: wiremock-studio-claim

      containers:
        - name: wiremock-studio
          image: up9inc/wiremock-studio:2.32.0-17
          args: ["--verbose"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: "/home/wiremock"
              name: wiremock-data-storage
          livenessProbe:
            httpGet:
              path: /status
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /status
              port: 9000
            initialDelaySeconds: 10
            periodSeconds: 3
      nodeSelector:
        kubernetes.io/os: linux

---
apiVersion: v1
kind: Service
metadata:
  name: wiremock-studio
  labels:
    name: wiremock-studio
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 9000
  selector:
    name: wiremock-studio
  sessionAffinity: None
  type: LoadBalancer

