version: "3.9"
# https://docs.docker.com/compose/compose-file/

x-common-variables: &common-variables
  JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=60.0
  SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  USERCTX_KEY: JWTSecretKeyDontUseInProduction!
  eureka.client.serviceUrl.defaultZone: http://registry:8080/eureka
  eureka.instance.non-secure-port: 8080
  management.endpoints.web.exposure.include: info,health,beans,bindings,gateway
  spring.main.banner-mode: off

x-database-variables: &database-variables
  spring.liquibase.enabled: 'true'
  spring.datasource.username: root
  spring.datasource.password: root
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

x-message-broker-variables: &message-broker-variables
  spring.activemq.broker-url: tcp://message-broker:61616
  spring.activemq.user: admin
  spring.activemq.password: admin

x-healthcheck-defaults: &healthcheck-defaults
  test: [ "CMD", "java", "/tmp/HealthCheck.java" ]
  start_period: 60s
  interval: 30s
  timeout: 5s
  retries: 10

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.30
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - backbase_mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping --silent
      interval: 10s
      timeout: 5s
      retries: 5

  message-broker:
    container_name: activemq
    image: symptoma/activemq:5.17.1
    privileged: true
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
      - "61613:61613"
      - "1883:1883"
      - "61614:61614"

  registry:
    container_name: registry
    image: repo.backbase.com/backbase-docker-releases/registry:${BB_VERSION}
    ports:
      - "8761:8080"

  edge:
    container_name: edge
    image: repo.backbase.com/backbase-docker-releases/edge:${BB_VERSION}
    ports:
      - "8280:8080"
    environment:
      <<: *common-variables
      gateway.actuator.user: "admin"
      gateway.actuator.password: "admin"
      gateway.csrf.enabled: "false"
      spring.cloud.gateway.globalcors.corsConfigurations.'[/**]'.allowedOrigins: "*"
      spring.cloud.gateway.globalcors.corsConfigurations.'[/**]'.allowedHeaders: "*"
      spring.cloud.gateway.globalcors.corsConfigurations.'[/**]'.allowedMethods: "*"
    links:
      - registry
      - token-converter

  token-converter:
    container_name: token_converter
    image: repo.backbase.com/backbase-docker-releases/oidc-token-converter-service:${BB_VERSION}
    ports:
      - "7779:8080"
    environment:
      <<: *common-variables
      BACKBASE_OIDCTOKENCONVERTER_WHITELISTEDDOMAINS_0_INTERNALHOSTSCHEME: "http"
      BACKBASE_OIDCTOKENCONVERTER_WHITELISTEDDOMAINS_0_INTERNALHOST: "identity:8080"
      BACKBASE_OIDCTOKENCONVERTER_WHITELISTEDDOMAINS_0_ISSUERHOST: "localhost"
    volumes:
      - ./scripts/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
    links:
      - registry
      - identity

  identity:
    container_name: identity
    image: repo.backbase.com/backbase-docker-releases/backbase-identity:${BB_VERSION}
    ports:
      - '8180:8080'
    environment:
      QUARKUS_DATASOURCE_URL: "jdbc:mysql://mysql:3306/backbase_identity?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true"
      QUARKUS_DATASOURCE_USERNAME: "root"
      QUARKUS_DATASOURCE_PASSWORD: "root"
      QUARKUS_DATASOURCE_DRIVER: "com.mysql.cj.jdbc.Driver"
      QUARKUS_LOG_FILE_ENABLE: "false"
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_HOME_DIR: "/"
      KEYCLOAK_CONNECTIONSJPA_QUARKUS_INITIALIZEEMPTY: "true"
      KEYCLOAK_CONNECTIONSJPA_QUARKUS_MIGRATIONSTRATEGY: "update"
      KEYCLOAK_BACKBASE_OIDC_TOKEN_CONVERTER_URL: "http://token-converter:8080"
      keycloak.hostname.default.frontendUrl: "http://localhost:8180/auth"
      JAVA_TOOL_OPTIONS: "-Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.action=import -Dkeycloak.profile.feature.upload_scripts=enabled -Dquarkus.log.category.'\"com.backbase\"'.level=DEBUG -Dquarkus.log.category.'\"org.keycloak.protocol.oidc\"'.level=TRACE"
    volumes:
      - ../config/identity:/tmp/keycloak-export
      - ./scripts/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      test: [ "CMD", "java", "/tmp/HealthCheck.java", "http://localhost:8080/auth/q/health/ready" ]
      start_period: 60s
      interval: 30s
      timeout: 5s
      retries: 10
    depends_on:
      mysql:
        condition: service_healthy

  access-control:
    container_name: access_control
    image: repo.backbase.com/backbase-docker-releases/access-control:${BB_VERSION}
    ports:
      - "8040:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      <<: *database-variables
      spring.datasource.url: jdbc:mysql://mysql:3306/access-control?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
    volumes:
      - ./scripts/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - message-broker
      - registry

  arrangement-manager:
    container_name: arrangement_manager
    image: repo.backbase.com/backbase-docker-releases/arrangement-manager:${BB_VERSION}
    ports:
      - "8050:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      <<: *database-variables
      spring.datasource.url: jdbc:mysql://mysql:3306/arrangement-manager?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
    volumes:
      - ./scripts/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - message-broker
      - registry

  user-manager:
    container_name: user_manager
    image: repo.backbase.com/backbase-docker-releases/user-manager:${BB_VERSION}
    ports:
      - "8060:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      <<: *database-variables
      spring.datasource.url: jdbc:mysql://mysql:3306/user-manager?useSSL=false&allowPublicKeyRetrieval=true&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      BACKBASE_USERS_IDENTITYENDPOINTSENABLED: "true"
      BACKBASE_USERS_IDENTITYINTEGRATIONENABLED: "true"
    volumes:
      - ./scripts/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
    depends_on:
      mysql:
        condition: service_healthy
    links:
      - message-broker
      - registry

  identity-integration-service:
    container_name: identity_integration_service
    image: repo.backbase.com/backbase-docker-releases/identity-integration-service:${BB_VERSION}
    ports:
      - "8070:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      IDENTITY_SERVERURL: http://identity:8080/auth
      IDENTITY_MASTERADMIN_USERNAME: admin
      IDENTITY_MASTERADMIN_PASSWORD: admin
      IDENTITY_MASTERADMIN_REALMNAME: master
      IDENTITY_MASTERADMIN_CLIENTID: admin-cli
      IDENTITY_REALMCONFIGURATION_FALLBACKOPTIONS_ENABLEUSER: "true"
      IDENTITY_REALMCONFIGURATION_FALLBACKOPTIONS_USETEMPORARYPASSWORD: "true"
    volumes:
      - ./scripts/HealthCheck.java:/tmp/HealthCheck.java
    healthcheck:
      <<: *healthcheck-defaults
    links:
      - message-broker
      - registry

  employee-app:
    container_name: employee_app
    image: harbor.backbase.eu/development/employee-web-app-essentials:2022.08.1-LTS
    environment:
      AUTH_URL: "http://localhost:8180/auth"
      API_ROOT: "http://localhost:8080/api"
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/api.conf:/nginx-config/server/15-api.conf
    links:
      - edge
      - identity

  legal-entity-bootstrap-task:
    container_name: legal_entity_bootstrap_task
    image: repo.backbase.com/backbase-stream-images/legal-entity-bootstrap-task:3.2.0
    profiles:
      - bootstrap
    environment:
      <<: *common-variables
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=70.0 -Dlogging.level.com.backbase.stream=DEBUG"
      SPRING_PROFILES_INCLUDE: "moustache-bank"
    depends_on:
      token-converter:
        condition: service_healthy
      access-control:
        condition: service_healthy
      arrangement-manager:
        condition: service_healthy
      user-manager:
        condition: service_healthy
      identity-integration-service:
        condition: service_healthy
      identity:
        condition: service_healthy

volumes:
  backbase_mysql_data:
    driver: local

networks:
  default:
    name: backbase_default
