version: "3.7"
# https://docs.docker.com/compose/compose-file/

x-common-variables: &common-variables
  SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  EXTERNAL_SIG_SECRET_KEY: JWTSecretKeyDontUseInProduction!
  EXTERNAL_ENC_SECRET_KEY: JWTEncKeyDontUseInProduction666!
  eureka.client.serviceUrl.defaultZone: http://registry:8080/eureka
  eureka.instance.non-secure-port: 8080
  management.endpoints.web.exposure.include: info,health,beans,bindings,gateway
  SPRING_MAIN_BANNER-MODE: 'off'

x-database-variables: &database-variables
  spring.liquibase.enabled: 'true'
  spring.datasource.username: root
  spring.datasource.password: root
  spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
  spring.jpa.database-platform: org.hibernate.dialect.MySQL5Dialect
  spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

x-message-broker-variables: &message-broker-variables
  spring.activemq.broker-url: tcp://message-broker:61616
  spring.activemq.user: admin
  spring.activemq.password: admin

services:

  message-broker:
    image: symptoma/activemq:5.17.0
    container_name: demo_activemq
    privileged: true
    ports:
      - "61616:61616"
      - "8161:8161"
      - "5672:5672"
      - "61613:61613"
      - "1883:1883"
      - "61614:61614"

  mysql:
    image: mysql:5.7.18
    # Set max_allowed_packet to 512M for provisioning
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8_bin' --init-connect='SET NAMES utf8;' --character-set-server=utf8 --collation-server=utf8_bin --lower-case-table-names=2 --max-connections=500
    container_name: demo_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - demo_mysql_data:/var/lib/mysql

  edge:
    image: repo.backbase.com/backbase-docker-releases/edge:${BB_VERSION}
    ports:
      - "8080:8080"
    environment:
      <<: *common-variables
      gateway.actuator.user: admin
      gateway.actuator.password: admin
      spring.cloud.gateway.globalcors.corsConfigurations.'[/**]'.allowedOrigins: "*"
      spring.cloud.gateway.globalcors.corsConfigurations.'[/**]'.allowedHeaders: "*"
      spring.cloud.gateway.globalcors.corsConfigurations.'[/**]'.allowedMethods: "*"
    links:
      - registry
      - token-converter
  
  registry:
    image: repo.backbase.com/backbase-docker-releases/registry:${BB_VERSION}
    ports:
      - "8761:8080"

  token-converter:
    image: repo.backbase.com/backbase-docker-releases/oidc-token-converter-service:${BB_VERSION}
    ports:
      - "7779:8080"
    environment:
      <<: *common-variables
    links:
      - registry

  identity:
    image: repo.backbase.com/backbase-docker-releases/backbase-identity:${BB_VERSION}
    container_name: identity
    environment:
      KEYCLOAK_BACKBASE_OIDC_TOKEN_CONVERTER_URL: "http://token-converter:8080"
      # KEYCLOAK_BACKBASE_EVENT_LISTENERS_AUDIT_INTEGRATIONSERVICEURL: "http://host.docker.internal:8092/audit-service"
      # KEYCLOAK_BACKBASE_DEVICE_URL: "http://host.docker.internal:8181/device-management-service"
      # KEYCLOAK_BACKBASE_FIDO_URL: "http://host.docker.internal:8181/fido-service"
      QUARKUS_DATASOURCE_URL: "jdbc:mysql://mysql:3306/backbase_identity?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true"
      QUARKUS_DATASOURCE_USERNAME: "root"
      QUARKUS_DATASOURCE_PASSWORD: "root"
      QUARKUS_DATASOURCE_DRIVER: "com.mysql.cj.jdbc.Driver"
      QUARKUS_LOG_FILE_ENABLE: "false"
      keycloak.hostname.default.frontendUrl: http://localhost:8180/auth
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      KEYCLOAK_CONNECTIONSJPA_QUARKUS_INITIALIZEEMPTY: "true"
      KEYCLOAK_CONNECTIONSJPA_QUARKUS_MIGRATIONSTRATEGY: "update"
      KEYCLOAK_HOME_DIR: "/" 
      JAVA_TOOL_OPTIONS: "-Dkeycloak.migration.strategy=IGNORE_EXISTING -Dkeycloak.migration.action=import -Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - '8180:8080'
      - '10090:10090'
    volumes:
      - ../config:/tmp/keycloak-export
    links:
      - mysql
      - token-converter

  access-control:
    image: repo.backbase.com/backbase-docker-releases/access-control:${BB_VERSION}
    hostname: accesscontrol
    ports:
      - "8040:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      <<: *database-variables
      spring.datasource.url: jdbc:mysql://mysql:3306/access-control?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      USERCTX_KEY: JWTSecretKeyDontUseInProduction!
    links:
      - mysql
      - registry
      - message-broker

  arrangement-manager:
    image: repo.backbase.com/backbase-docker-releases/arrangement-manager:${BB_VERSION}
    hostname: arrangementmanager
    ports:
      - "8050:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      <<: *database-variables
      spring.datasource.url: jdbc:mysql://mysql:3306/arrangement-manager?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
    links:
      - mysql
      - registry
      - message-broker

  user-manager:
    image: repo.backbase.com/backbase-docker-releases/user-manager:${BB_VERSION}
    hostname: arrangementmanager
    ports:
      - "8060:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      <<: *database-variables
      spring.datasource.url: jdbc:mysql://mysql:3306/user-manager?useSSL=false&cacheServerConfiguration=true&createDatabaseIfNotExist=true
      BACKBASE_USERS_IDENTITYENDPOINTSENABLED: "true"
      BACKBASE_USERS_IDENTITYINTEGRATIONENABLED: "true"
    links:
      - mysql
      - registry
      - message-broker

  identity-integration-service:
    image: repo.backbase.com/backbase-docker-releases/identity-integration-service:${BB_VERSION}
    hostname: identityintegration
    ports:
      - "8070:8080"
    environment:
      <<: *common-variables
      <<: *message-broker-variables
      IDENTITY_SERVERURL: http://identity:8080/auth
      IDENTITY_MASTERADMIN_USERNAME: admin
      IDENTITY_MASTERADMIN_PASSWORD: admin
      IDENTITY_MASTERADMIN_REALMNAME: master
      IDENTITY_MASTERADMIN_CLIENTID: admin-cli
      IDENTITY_REALMCONFIGURATION_FALLBACKOPTIONS_ENABLEUSER: "true"
      IDENTITY_REALMCONFIGURATION_FALLBACKOPTIONS_USETEMPORARYPASSWORD: "true"
    links:
      - registry
      - message-broker

  
  retail-bootstrap-task:
    image: harbor.backbase.eu/development/moustache-bootstrap-task:2.82.0
    environment:
      SPRING_PROFILES_INCLUDE: ''
      JAVA_TOOL_OPTIONS: -XX:MaxRAMPercentage=70.0 -XX:+UseContainerSupport
      DBS_TOKEN_URI: http://token-converter:8080/oauth/token
      ADMIN_BASEPATH: http://identity:8080/auth
      BACKBASE_STREAM_IDENTITY_IDENTITYINTEGRATIONBASEURL: http://identity-integration-service:8080
      BACKBASE_STREAM_DBS_ACCESSCONTROLBASEURL: http://access-control:8080
      BACKBASE_STREAM_DBS_ARRANGEMENTMANAGERBASEURL: http://arrangement-manager:8080
      BACKBASE_STREAM_DBS_USERMANAGERBASEURL: http://user-manager:8080
  

  employee-app:
    image: harbor.backbase.eu/development/employee-web-app-essentials:2022.06
    environment:
      AUTH_URL: "http://localhost:8180/auth"
      API_ROOT: "http://localhost:8080/api"
    ports:
      - '8280:8080'


volumes:
  demo_mysql_data: